# Generated by Django 4.2.5 on 2023-09-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='price'),
        ),
    ]
