# Generated by Django 4.2.5 on 2023-10-05 12:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partservice',
            name='about',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=10000, verbose_name='about'),
        ),
    ]
