# Generated by Django 4.2.5 on 2023-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_partservicereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='partservice',
            name='problem',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='problem'),
        ),
    ]
