# Generated by Django 4.2.5 on 2023-10-09 13:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0007_partservice_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partservice',
            name='problem',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=10000, verbose_name='problem'),
        ),
        migrations.CreateModel(
            name='CarPartService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_part_services', to='autoservisas.car')),
                ('part_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_part_services', to='autoservisas.partservice')),
            ],
        ),
    ]
